// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ComputeStandings(arg1) {
  return window['go']['main']['App']['ComputeStandings'](arg1);
}

export function CreateCompetition(arg1) {
  return window['go']['main']['App']['CreateCompetition'](arg1);
}

export function CreateParticipant(arg1, arg2) {
  return window['go']['main']['App']['CreateParticipant'](arg1, arg2);
}

export function CreateStage(arg1, arg2) {
  return window['go']['main']['App']['CreateStage'](arg1, arg2);
}

export function CreateTeam(arg1, arg2) {
  return window['go']['main']['App']['CreateTeam'](arg1, arg2);
}

export function DeleteCompetition(arg1) {
  return window['go']['main']['App']['DeleteCompetition'](arg1);
}

export function DeleteParticipant(arg1) {
  return window['go']['main']['App']['DeleteParticipant'](arg1);
}

export function DeleteStage(arg1) {
  return window['go']['main']['App']['DeleteStage'](arg1);
}

export function DeleteTeam(arg1) {
  return window['go']['main']['App']['DeleteTeam'](arg1);
}

export function ExportAllCompetitionsResults() {
  return window['go']['main']['App']['ExportAllCompetitionsResults']();
}

export function ExportOverallResults(arg1) {
  return window['go']['main']['App']['ExportOverallResults'](arg1);
}

export function ExportStageResults(arg1) {
  return window['go']['main']['App']['ExportStageResults'](arg1);
}

export function FormatTime(arg1) {
  return window['go']['main']['App']['FormatTime'](arg1);
}

export function GetCompetitionByID(arg1) {
  return window['go']['main']['App']['GetCompetitionByID'](arg1);
}

export function GetIndividualStandings(arg1) {
  return window['go']['main']['App']['GetIndividualStandings'](arg1);
}

export function GetParticipantByID(arg1) {
  return window['go']['main']['App']['GetParticipantByID'](arg1);
}

export function GetParticipantResults(arg1, arg2) {
  return window['go']['main']['App']['GetParticipantResults'](arg1, arg2);
}

export function GetParticipantsWithResults(arg1, arg2) {
  return window['go']['main']['App']['GetParticipantsWithResults'](arg1, arg2);
}

export function GetStageByID(arg1) {
  return window['go']['main']['App']['GetStageByID'](arg1);
}

export function GetStageResults(arg1) {
  return window['go']['main']['App']['GetStageResults'](arg1);
}

export function GetStageStandings(arg1) {
  return window['go']['main']['App']['GetStageStandings'](arg1);
}

export function GetStageStandingsWithParticipants(arg1) {
  return window['go']['main']['App']['GetStageStandingsWithParticipants'](arg1);
}

export function GetTeamByID(arg1) {
  return window['go']['main']['App']['GetTeamByID'](arg1);
}

export function ListCompetitions() {
  return window['go']['main']['App']['ListCompetitions']();
}

export function ListParticipants(arg1) {
  return window['go']['main']['App']['ListParticipants'](arg1);
}

export function ListStages(arg1) {
  return window['go']['main']['App']['ListStages'](arg1);
}

export function ListTeams(arg1) {
  return window['go']['main']['App']['ListTeams'](arg1);
}

export function ParseTimeToSeconds(arg1) {
  return window['go']['main']['App']['ParseTimeToSeconds'](arg1);
}

export function UpdateCompetition(arg1, arg2) {
  return window['go']['main']['App']['UpdateCompetition'](arg1, arg2);
}

export function UpdateParticipant(arg1, arg2) {
  return window['go']['main']['App']['UpdateParticipant'](arg1, arg2);
}

export function UpdateStage(arg1, arg2) {
  return window['go']['main']['App']['UpdateStage'](arg1, arg2);
}

export function UpdateTeam(arg1, arg2) {
  return window['go']['main']['App']['UpdateTeam'](arg1, arg2);
}

export function UpsertStageResult(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpsertStageResult'](arg1, arg2, arg3, arg4, arg5);
}
