// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function ComputeStandings(arg1:number):Promise<Array<database.OverallStanding>>;

export function CreateCompetition(arg1:database.Competition):Promise<database.Competition>;

export function CreateParticipant(arg1:number,arg2:database.Participant):Promise<database.Participant>;

export function CreateStage(arg1:number,arg2:string):Promise<database.Stage>;

export function CreateTeam(arg1:number,arg2:string):Promise<database.Team>;

export function DeleteCompetition(arg1:number):Promise<void>;

export function DeleteParticipant(arg1:number):Promise<void>;

export function DeleteStage(arg1:number):Promise<void>;

export function DeleteTeam(arg1:number):Promise<void>;

export function ExportAllCompetitionsResults():Promise<void>;

export function ExportOverallResults(arg1:number):Promise<void>;

export function ExportParticipantStatistics(arg1:number,arg2:number):Promise<void>;

export function ExportStageResults(arg1:number):Promise<void>;

export function ExportTeamStatistics(arg1:number,arg2:number):Promise<void>;

export function FormatTime(arg1:number):Promise<string>;

export function GetCompetitionByID(arg1:number):Promise<database.Competition>;

export function GetIndividualStandings(arg1:number):Promise<Array<database.IndividualStanding>>;

export function GetParticipantByID(arg1:number):Promise<database.Participant>;

export function GetParticipantResults(arg1:number,arg2:number):Promise<Array<database.ParticipantStageDetail>>;

export function GetParticipantStatistics(arg1:number,arg2:number):Promise<database.ParticipantStatistics>;

export function GetParticipantsWithResults(arg1:number,arg2:number):Promise<Array<database.ParticipantWithResults>>;

export function GetStageByID(arg1:number):Promise<database.Stage>;

export function GetStageResults(arg1:number):Promise<Array<database.StageResult>>;

export function GetStageStandings(arg1:number):Promise<Array<database.StageStanding>>;

export function GetStageStandingsWithParticipants(arg1:number):Promise<Array<database.StageStandingWithParticipants>>;

export function GetTeamByID(arg1:number):Promise<database.Team>;

export function GetTeamStatistics(arg1:number,arg2:number):Promise<database.TeamStatistics>;

export function ListCompetitions():Promise<Array<database.Competition>>;

export function ListParticipants(arg1:number):Promise<Array<database.Participant>>;

export function ListStages(arg1:number):Promise<Array<database.Stage>>;

export function ListTeams(arg1:number):Promise<Array<database.Team>>;

export function ParseTimeToSeconds(arg1:string):Promise<number>;

export function UpdateCompetition(arg1:number,arg2:database.Competition):Promise<database.Competition>;

export function UpdateParticipant(arg1:number,arg2:database.Participant):Promise<database.Participant>;

export function UpdateStage(arg1:number,arg2:string):Promise<database.Stage>;

export function UpdateTeam(arg1:number,arg2:string):Promise<database.Team>;

export function UpsertStageResult(arg1:number,arg2:number,arg3:number,arg4:number):Promise<database.StageResult>;
